version: '3.8'
services:
  flask-app:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    ports:
      - "8000:8000"

  express-app:
    build: ./express
    ports:
      - "3000:3000"
  locust:
     image: locustio/locust
     stop_signal: SIGINT
     ports:
       - "8089:8089"
     volumes:
       - ./:/mnt/locust
     command: -f /mnt/locust/locustfile.py 
    #  command: -f /mnt/locust/locustfile.py --host http://flask-app:8000

  # locust-express:
  #   image: locustio/locust
  #   stop_signal: SIGINT
  #   ports:
  #     - "8090:8089"
  #   volumes:
  #     - ./:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --host http://express-app:3000
